/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root.route'
import { Route as IndexRouteRouteImport } from './routes/index.route'
import { Route as ColorPickerIndexRouteRouteImport } from './routes/color-picker/index.route'
import { Route as DescriptionGameIdRouteRouteImport } from './routes/description/$gameId.route'

const IndexRouteRoute = IndexRouteRouteImport.update({
  id: '/',
  path: '',
  getParentRoute: () => rootRouteImport,
} as any)
const ColorPickerIndexRouteRoute = ColorPickerIndexRouteRouteImport.update({
  id: '/color-picker/',
  path: '/color-picker',
  getParentRoute: () => rootRouteImport,
} as any)
const DescriptionGameIdRouteRoute = DescriptionGameIdRouteRouteImport.update({
  id: '/description/$gameId',
  path: '/description/$gameId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRouteRoute
  '/description/$gameId': typeof DescriptionGameIdRouteRoute
  '/color-picker/': typeof ColorPickerIndexRouteRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRouteRoute
  '/description/$gameId': typeof DescriptionGameIdRouteRoute
  '/color-picker': typeof ColorPickerIndexRouteRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRouteRoute
  '/description/$gameId': typeof DescriptionGameIdRouteRoute
  '/color-picker/': typeof ColorPickerIndexRouteRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/description/$gameId' | '/color-picker/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/description/$gameId' | '/color-picker'
  id: '__root__' | '/' | '/description/$gameId' | '/color-picker/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRouteRoute: typeof IndexRouteRoute
  DescriptionGameIdRouteRoute: typeof DescriptionGameIdRouteRoute
  ColorPickerIndexRouteRoute: typeof ColorPickerIndexRouteRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/color-picker/': {
      id: '/color-picker/'
      path: '/color-picker'
      fullPath: '/color-picker/'
      preLoaderRoute: typeof ColorPickerIndexRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/description/$gameId': {
      id: '/description/$gameId'
      path: '/description/$gameId'
      fullPath: '/description/$gameId'
      preLoaderRoute: typeof DescriptionGameIdRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRouteRoute: IndexRouteRoute,
  DescriptionGameIdRouteRoute: DescriptionGameIdRouteRoute,
  ColorPickerIndexRouteRoute: ColorPickerIndexRouteRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
